//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWCFCRUD
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Get_Producto_Result", Namespace="http://schemas.datacontract.org/2004/07/WCF.Modelo")]
    public partial class Get_Producto_Result : object
    {
        
        private ServiceWCFCRUD.Categoria CategoriaField;
        
        private string DescripciónField;
        
        private System.Nullable<System.DateTime> Fecha_CreacionField;
        
        private System.Nullable<int> ID_CategoriaField;
        
        private int IdField;
        
        private byte[] ImagenField;
        
        private string InfoProductoField;
        
        private System.Nullable<double> Precio_CompraField;
        
        private System.Nullable<double> Precio_VentaField;
        
        private System.Nullable<int> StockField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceWCFCRUD.Categoria Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripción
        {
            get
            {
                return this.DescripciónField;
            }
            set
            {
                this.DescripciónField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha_Creacion
        {
            get
            {
                return this.Fecha_CreacionField;
            }
            set
            {
                this.Fecha_CreacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_Categoria
        {
            get
            {
                return this.ID_CategoriaField;
            }
            set
            {
                this.ID_CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen
        {
            get
            {
                return this.ImagenField;
            }
            set
            {
                this.ImagenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InfoProducto
        {
            get
            {
                return this.InfoProductoField;
            }
            set
            {
                this.InfoProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Precio_Compra
        {
            get
            {
                return this.Precio_CompraField;
            }
            set
            {
                this.Precio_CompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Precio_Venta
        {
            get
            {
                return this.Precio_VentaField;
            }
            set
            {
                this.Precio_VentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/WCF.Modelo")]
    public partial class Categoria : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        private ServiceWCFCRUD.Producto[] ProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceWCFCRUD.Producto[] Producto
        {
            get
            {
                return this.ProductoField;
            }
            set
            {
                this.ProductoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/WCF.Modelo")]
    public partial class Producto : object
    {
        
        private ServiceWCFCRUD.Categoria CategoriaField;
        
        private string DescripciónField;
        
        private System.Nullable<System.DateTime> Fecha_CreacionField;
        
        private System.Nullable<int> ID_CategoriaField;
        
        private int IdField;
        
        private byte[] ImagenField;
        
        private string InfoProductoField;
        
        private System.Nullable<double> Precio_CompraField;
        
        private System.Nullable<double> Precio_VentaField;
        
        private System.Nullable<int> StockField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceWCFCRUD.Categoria Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripción
        {
            get
            {
                return this.DescripciónField;
            }
            set
            {
                this.DescripciónField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha_Creacion
        {
            get
            {
                return this.Fecha_CreacionField;
            }
            set
            {
                this.Fecha_CreacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_Categoria
        {
            get
            {
                return this.ID_CategoriaField;
            }
            set
            {
                this.ID_CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen
        {
            get
            {
                return this.ImagenField;
            }
            set
            {
                this.ImagenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InfoProducto
        {
            get
            {
                return this.InfoProductoField;
            }
            set
            {
                this.InfoProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Precio_Compra
        {
            get
            {
                return this.Precio_CompraField;
            }
            set
            {
                this.Precio_CompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Precio_Venta
        {
            get
            {
                return this.Precio_VentaField;
            }
            set
            {
                this.Precio_VentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Get_All_Productos_Result", Namespace="http://schemas.datacontract.org/2004/07/WCF.Modelo")]
    public partial class Get_All_Productos_Result : object
    {
        
        private ServiceWCFCRUD.Categoria CategoriaField;
        
        private string DescripciónField;
        
        private System.Nullable<System.DateTime> Fecha_CreacionField;
        
        private System.Nullable<int> ID_CategoriaField;
        
        private int IdField;
        
        private byte[] ImagenField;
        
        private string InfoProductoField;
        
        private System.Nullable<double> Precio_CompraField;
        
        private System.Nullable<double> Precio_VentaField;
        
        private System.Nullable<int> StockField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceWCFCRUD.Categoria Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripción
        {
            get
            {
                return this.DescripciónField;
            }
            set
            {
                this.DescripciónField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha_Creacion
        {
            get
            {
                return this.Fecha_CreacionField;
            }
            set
            {
                this.Fecha_CreacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_Categoria
        {
            get
            {
                return this.ID_CategoriaField;
            }
            set
            {
                this.ID_CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen
        {
            get
            {
                return this.ImagenField;
            }
            set
            {
                this.ImagenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InfoProducto
        {
            get
            {
                return this.InfoProductoField;
            }
            set
            {
                this.InfoProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Precio_Compra
        {
            get
            {
                return this.Precio_CompraField;
            }
            set
            {
                this.Precio_CompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Precio_Venta
        {
            get
            {
                return this.Precio_VentaField;
            }
            set
            {
                this.Precio_VentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Get_All_Categoria_Result", Namespace="http://schemas.datacontract.org/2004/07/WCF.Modelo")]
    public partial class Get_All_Categoria_Result : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWCFCRUD.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducto", ReplyAction="http://tempuri.org/IService1/GetProductoResponse")]
        ServiceWCFCRUD.Get_Producto_Result GetProducto(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducto", ReplyAction="http://tempuri.org/IService1/GetProductoResponse")]
        System.Threading.Tasks.Task<ServiceWCFCRUD.Get_Producto_Result> GetProductoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllProductos", ReplyAction="http://tempuri.org/IService1/GetAllProductosResponse")]
        ServiceWCFCRUD.Get_All_Productos_Result[] GetAllProductos(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllProductos", ReplyAction="http://tempuri.org/IService1/GetAllProductosResponse")]
        System.Threading.Tasks.Task<ServiceWCFCRUD.Get_All_Productos_Result[]> GetAllProductosAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCat", ReplyAction="http://tempuri.org/IService1/GetAllCatResponse")]
        ServiceWCFCRUD.Get_All_Categoria_Result[] GetAllCat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCat", ReplyAction="http://tempuri.org/IService1/GetAllCatResponse")]
        System.Threading.Tasks.Task<ServiceWCFCRUD.Get_All_Categoria_Result[]> GetAllCatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCat", ReplyAction="http://tempuri.org/IService1/CreateCatResponse")]
        void CreateCat(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCat", ReplyAction="http://tempuri.org/IService1/CreateCatResponse")]
        System.Threading.Tasks.Task CreateCatAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCat", ReplyAction="http://tempuri.org/IService1/UpdateCatResponse")]
        void UpdateCat(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCat", ReplyAction="http://tempuri.org/IService1/UpdateCatResponse")]
        System.Threading.Tasks.Task UpdateCatAsync(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCat", ReplyAction="http://tempuri.org/IService1/DeleteCatResponse")]
        void DeleteCat(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCat", ReplyAction="http://tempuri.org/IService1/DeleteCatResponse")]
        System.Threading.Tasks.Task DeleteCatAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateProd", ReplyAction="http://tempuri.org/IService1/CreateProdResponse")]
        void CreateProd(byte[] imagen, string descripción, System.Nullable<double> precio_Compra, System.Nullable<double> precio_Venta, System.Nullable<int> stock, System.Nullable<int> iD_Categoria, string infoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateProd", ReplyAction="http://tempuri.org/IService1/CreateProdResponse")]
        System.Threading.Tasks.Task CreateProdAsync(byte[] imagen, string descripción, System.Nullable<double> precio_Compra, System.Nullable<double> precio_Venta, System.Nullable<int> stock, System.Nullable<int> iD_Categoria, string infoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProd", ReplyAction="http://tempuri.org/IService1/UpdateProdResponse")]
        void UpdateProd(int id, byte[] imagen, string descripción, System.Nullable<double> precio_Compra, System.Nullable<double> precio_Venta, System.Nullable<int> stock, System.Nullable<int> iD_Categoria, string infoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProd", ReplyAction="http://tempuri.org/IService1/UpdateProdResponse")]
        System.Threading.Tasks.Task UpdateProdAsync(int id, byte[] imagen, string descripción, System.Nullable<double> precio_Compra, System.Nullable<double> precio_Venta, System.Nullable<int> stock, System.Nullable<int> iD_Categoria, string infoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProd", ReplyAction="http://tempuri.org/IService1/DeleteProdResponse")]
        void DeleteProd(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProd", ReplyAction="http://tempuri.org/IService1/DeleteProdResponse")]
        System.Threading.Tasks.Task DeleteProdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ServiceWCFCRUD.CompositeType GetDataUsingDataContract(ServiceWCFCRUD.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServiceWCFCRUD.CompositeType> GetDataUsingDataContractAsync(ServiceWCFCRUD.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IService1Channel : ServiceWCFCRUD.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceWCFCRUD.IService1>, ServiceWCFCRUD.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public ServiceWCFCRUD.Get_Producto_Result GetProducto(int Id)
        {
            return base.Channel.GetProducto(Id);
        }
        
        public System.Threading.Tasks.Task<ServiceWCFCRUD.Get_Producto_Result> GetProductoAsync(int Id)
        {
            return base.Channel.GetProductoAsync(Id);
        }
        
        public ServiceWCFCRUD.Get_All_Productos_Result[] GetAllProductos(int Id)
        {
            return base.Channel.GetAllProductos(Id);
        }
        
        public System.Threading.Tasks.Task<ServiceWCFCRUD.Get_All_Productos_Result[]> GetAllProductosAsync(int Id)
        {
            return base.Channel.GetAllProductosAsync(Id);
        }
        
        public ServiceWCFCRUD.Get_All_Categoria_Result[] GetAllCat()
        {
            return base.Channel.GetAllCat();
        }
        
        public System.Threading.Tasks.Task<ServiceWCFCRUD.Get_All_Categoria_Result[]> GetAllCatAsync()
        {
            return base.Channel.GetAllCatAsync();
        }
        
        public void CreateCat(string name)
        {
            base.Channel.CreateCat(name);
        }
        
        public System.Threading.Tasks.Task CreateCatAsync(string name)
        {
            return base.Channel.CreateCatAsync(name);
        }
        
        public void UpdateCat(int id, string name)
        {
            base.Channel.UpdateCat(id, name);
        }
        
        public System.Threading.Tasks.Task UpdateCatAsync(int id, string name)
        {
            return base.Channel.UpdateCatAsync(id, name);
        }
        
        public void DeleteCat(int Id)
        {
            base.Channel.DeleteCat(Id);
        }
        
        public System.Threading.Tasks.Task DeleteCatAsync(int Id)
        {
            return base.Channel.DeleteCatAsync(Id);
        }
        
        public void CreateProd(byte[] imagen, string descripción, System.Nullable<double> precio_Compra, System.Nullable<double> precio_Venta, System.Nullable<int> stock, System.Nullable<int> iD_Categoria, string infoProducto)
        {
            base.Channel.CreateProd(imagen, descripción, precio_Compra, precio_Venta, stock, iD_Categoria, infoProducto);
        }
        
        public System.Threading.Tasks.Task CreateProdAsync(byte[] imagen, string descripción, System.Nullable<double> precio_Compra, System.Nullable<double> precio_Venta, System.Nullable<int> stock, System.Nullable<int> iD_Categoria, string infoProducto)
        {
            return base.Channel.CreateProdAsync(imagen, descripción, precio_Compra, precio_Venta, stock, iD_Categoria, infoProducto);
        }
        
        public void UpdateProd(int id, byte[] imagen, string descripción, System.Nullable<double> precio_Compra, System.Nullable<double> precio_Venta, System.Nullable<int> stock, System.Nullable<int> iD_Categoria, string infoProducto)
        {
            base.Channel.UpdateProd(id, imagen, descripción, precio_Compra, precio_Venta, stock, iD_Categoria, infoProducto);
        }
        
        public System.Threading.Tasks.Task UpdateProdAsync(int id, byte[] imagen, string descripción, System.Nullable<double> precio_Compra, System.Nullable<double> precio_Venta, System.Nullable<int> stock, System.Nullable<int> iD_Categoria, string infoProducto)
        {
            return base.Channel.UpdateProdAsync(id, imagen, descripción, precio_Compra, precio_Venta, stock, iD_Categoria, infoProducto);
        }
        
        public void DeleteProd(int Id)
        {
            base.Channel.DeleteProd(Id);
        }
        
        public System.Threading.Tasks.Task DeleteProdAsync(int Id)
        {
            return base.Channel.DeleteProdAsync(Id);
        }
        
        public ServiceWCFCRUD.CompositeType GetDataUsingDataContract(ServiceWCFCRUD.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ServiceWCFCRUD.CompositeType> GetDataUsingDataContractAsync(ServiceWCFCRUD.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:49915/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
